"""creation of vote table and ower_relationship in insta_posts table

Revision ID: 65891cf41d67
Revises: 708a0826bfd4
Create Date: 2023-06-08 12:56:44.230732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65891cf41d67'
down_revision = '708a0826bfd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('vote_post_id', sa.Integer(), nullable=False),
    sa.Column('vote_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vote_post_id'], ['insta_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vote_user_id'], ['insta_users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vote_post_id', 'vote_user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###
